### ISSUE TITLE
No such table: webtable_user

### ISSUE THREAD

**Issue by frankforp** [sunnywalden/xlsx_over_web#1]
![image](https://user-images.githubusercontent.com/5992008/70623419-0d5bab80-1c59-11ea-9755-053019116d68.png)

Could you please help this problem?

**Comment by sunnywalden** [comment]
> ![image](https://user-images.githubusercontent.com/5992008/70623419-0d5bab80-1c59-11ea-9755-053019116d68.png)
> 
> Could you please help this problem?

Sorry, it's my fault. I uploaded databse file and django migratons records into the project. Follow these steps below, may get you out of the trouble.
1)update code;

Ensure that there's no .py file in the migrations directory in webtable.
2) Update database;

python manage.py makemigrations

python manage.py migrate

3)Then, run the project directly.

**Comment by frankforp** [comment]
Thank you very much!!!
